[package]
name = "artifactory-rust-example-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artifactory_rust_example_lib = { version = "0.1.0", registry = "artifactory"}
